feat: connect mongoDB
KezzleCake/Kezzle-API pull request #6
Opened 2023-07-25 14:55 UTC by clscls09963

몽고디비 로컬로 연결함~

2023-07-25 15:21 UTC, HanHyunsoo requested changes
댓글 읽고 한개씩 고쳐보세요 잘했어요 굳굳

2023-07-25 15:21 UTC, HanHyunsoo commented on src/app.module.ts
> +    MongooseModule.forRoot(process.env.MONGODB_URL, { dbName: 'kezzle' }),
몽고디비 아이디, 비밀번호 무조건 걸기!
그리고 dbname도 환경변수에서 불러오기!

2023-07-25 15:21 UTC, HanHyunsoo commented on src/user/dto/create-user.dto.ts
> +  is_buyer: boolean;
Role관련은 request에 없어야될듯? cake likes, store likes도 마찬가지

2023-07-25 15:21 UTC, HanHyunsoo commented on src/user/entities/user.schema.ts
> +  roles: {
Object type을 지정해도되지만 Enum형태의 Array로 관리하면 좀더 좋은 코드가 나올거같아요

2023-07-25 15:21 UTC, HanHyunsoo commented on src/user/entities/user.schema.ts
> +  cake_like_ids: string[];
Default값으로 빈배열로, store도 마찬가지!

2023-07-25 15:21 UTC, HanHyunsoo commented on src/user/user.service.spec.ts
> +import { Test, TestingModule } from '@nestjs/testing';
이 파일은 테스트코드 관련이라 없애도될거같아

2023-07-25 15:21 UTC, HanHyunsoo commented on src/app.module.ts
> +  providers: [],
{
      provide: APP_PIPE,
      useClass: ValidationPipe,
    },

이걸로 main에 있는 검증파이프 리팩토링할 수 있음

2023-07-25 15:21 UTC, HanHyunsoo commented on src/main.ts
> +  app.useGlobalPipes(new ValidationPipe());
appmodule comment 참조

2023-07-25 15:21 UTC, HanHyunsoo commented on src/user/dto/update-user.dto.ts
> +export class UpdateUserDto {
Update용 Dto는 username만 잇으면 될거같아

2023-07-25 15:21 UTC, HanHyunsoo commented on src/user/dto/user.dto.ts
> +export class UpdateUserDto {
똑같은 클래스 또있는듯?

2023-07-25 15:21 UTC, HanHyunsoo commented on src/user/entities/user.schema.ts
> +@Schema({ timestamps: true }) // timestamps: createdAt과 updatedAt을 자동으로 생성
versionKey: false 추가고고

2023-07-25 15:58 UTC, Hyeyeon-Kim commented on src/user/dto/create-user.dto.ts
> +  is_buyer: boolean;
근데 cake likes랑 store likes는 있어야 하지않을까?
우리 나중에 찜 목록 보여줘야하자나
아닌가?
스토어 아이디로 데이터들 찾은걸 넘겨줘야하는 건가?

2023-07-25 16:14 UTC, clscls09963 commented on src/app.module.ts
> +  providers: [],
근데 main에서 app.module로 옮기는 이유가 뭐야ㅑㅑ?

2023-07-26 06:36 UTC, HanHyunsoo commented on src/user/dto/create-user.dto.ts
> +  is_buyer: boolean;
@clscls09963 그 부분은 response로 보여주면 될거같고 요청(POST)일때는 필요없을거같음

2023-07-26 06:36 UTC, HanHyunsoo commented on src/app.module.ts
> +  providers: [],
@clscls09963 DI 패턴으로 좀더 명확하게 구분하는게 좋을거같아서. 보통 main함수는 최대한 안건드리는게 좋긴해~

2023-07-30 08:55 UTC, HanHyunsoo requested changes
not good

2023-07-31 08:28 UTC, HanHyunsoo approved these changes
LGTM

2023-07-31 09:05 UTC, merged